<?php
$typeArr[9] = 'Career Development Events';
$typeArr[10] = 'About us_old';
$typeArr[6] = 'Culture Events';
$typeArr[11] = 'Columbia-China Forum';
$typeArr[12] = 'Join Us_old';
$typeArr[13] = 'BBS_old';
$typeArr[14] = 'Photo Gallery_old';
$typeArr[15] = 'Forums_old';
$typeArr[16] = 'Columbia China Prospects Confe';
$typeArr[17] = 'Columbia Business Conference';
$typeArr[20] = 'Events_old';
$typeArr[21] = 'Social Events';
$typeArr[22] = 'Columbia Night';
$typeArr[23] = 'Team_old';
$typeArr[24] = 'Contact US_old';
$typeArr[25] = 'Join_US_old';
$typeArr[26] = 'About';
$typeArr[27] = 'Events';
$typeArr[28] = 'Photo Gallery';
$typeArr[29] = 'Newsletters';
?>