<?php
$tmpdir = "2c95bfc956eeeb17";
$vtime = 20130422;
$files[0] = "include/dialog/config.php";
$files[1] = "member/inc/space_action.php";
$files[2] = "plus/feedback.php";
$files[3] = "include/payment/alipay.php";
$files[4] = "include/payment/yeepay.php";
$files[5] = "plus/search.php";
$files[6] = "include/arc.searchview.class.php";
$files[7] = "member/myfriend_group.php";
$files[8] = "plus/feedback_ajax.php";
$files[9] = "include/dedesql.class.php";
$files[10] = "include/dedesqli.class.php";
$files[11] = "plus/guestbook/edit.inc.php";
$files[12] = "include/common.inc.php";
$fileConut = 12;
$sqls[] = "20121115.sql";
$sqls[] = "20121122.sql";
$sqls[] = "20121218.sql";
$sqls[] = "20130115.sql";
$sqls[] = "20130121.sql";
$sqls[] = "20130304.sql";
$sqls[] = "20130401.sql";
$sqls[] = "20130402.sql";
$sqls[] = "20130422.sql";
?>