<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="5";
$z[0][4]['col']="3";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/111026/3-111026131U2.jpg ",93,241);
$z[1][4]['ddimg']="/uploads/allimg/111026/3-111026131U2-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="710";
$z[1][4]['height']="473";
$z[2]=Array("img"," /uploads/allimg/111026/3-111026131U4.jpg ",243,391);
$z[2][4]['ddimg']="/uploads/allimg/111026/3-111026131U4-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="710";
$z[2][4]['height']="473";
$z[3]=Array("img"," /uploads/allimg/111026/3-111026131U4-50.jpg ",393,547);
$z[3][4]['ddimg']="/uploads/allimg/111026/3-111026131U4-50-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="710";
$z[3][4]['height']="473";
$z[4]=Array("img"," /uploads/allimg/111026/3-111026131U5.jpg ",549,697);
$z[4][4]['ddimg']="/uploads/allimg/111026/3-111026131U5-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="710";
$z[4][4]['height']="473";
$z[5]=Array("img"," /uploads/allimg/111026/3-111026131U6.jpg ",699,847);
$z[5][4]['ddimg']="/uploads/allimg/111026/3-111026131U6-lp.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="710";
$z[5][4]['height']="532";

?>