{dede:specnote imgheight='90' imgwidth='120'
                infolen='160' titlelen='60' col='1' idlist=''
                name='默认节点' noteid='default' isauto='0' rownum='10'
                keywords='' typeid='0'}
                <li><span class="date">[field:typename/]</span><a href="[field:arcurl /]" target="_blank">[field:title /]</a></li>

<div style="display:none"><a href="http://www.cuasia.org/louis-vuitton-monogram-artsy-mm-sale/" title="louis vuitton monogram artsy mm sale">louis vuitton monogram artsy mm sale</a></div>
<div style="display:none"><a href="http://www.cuasia.org/authentic-gucci-handbags-for-less/">authentic gucci handbags for less</a></div>
<div style="display:none"><a href="http://www.cuasia.org/air-jordan-shoes-11-luggage-for-cheap/">air jordan shoes 11 luggage for cheap</a></div>
                {/dede:specnote}
