<?php
$z[0]=Array("specnote","\r\n                <li><span class=\"date\">[field:typename/]</span><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n\r\n<div style=\"display:none\"><a href=\"http://www.cuasia.org/louis-vuitton-monogram-artsy-mm-sale/\" title=\"louis vuitton monogram artsy mm sale\">louis vuitton monogram artsy mm sale</a></div>\r\n<div style=\"display:none\"><a href=\"http://www.cuasia.org/authentic-gucci-handbags-for-less/\">authentic gucci handbags for less</a></div>\r\n<div style=\"display:none\"><a href=\"http://www.cuasia.org/air-jordan-shoes-11-luggage-for-cheap/\">air jordan shoes 11 luggage for cheap</a></div>\r\n                ",0,866);
$z[0][4]['imgheight']="90";
$z[0][4]['imgwidth']="120";
$z[0][4]['infolen']="160";
$z[0][4]['titlelen']="60";
$z[0][4]['col']="1";
$z[0][4]['idlist']="";
$z[0][4]['name']="默认节点";
$z[0][4]['noteid']="default";
$z[0][4]['isauto']="0";
$z[0][4]['rownum']="10";
$z[0][4]['keywords']="";
$z[0][4]['typeid']="0";

?>