<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",13,90);
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",114,130);
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",132,217);
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",245,260);
$z[4]=Array("imgwidth","",274,292);
$z[5]=Array("linkurl","",354,370);
$z[6]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",372,458);
$z[6][4]['runphp']="yes";
$z[7]=Array("alttext","",472,488);
$z[8]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",505,585);
$z[8][4]['runphp']="yes";

?>