<div class="media ca-div-padding">
          [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='pull-left'><img class='media-object' src='{@me['litpic']}'/></a>"); [/field:array]
          <div class="media-body ca-div-margin">
            <h4 class="media-heading">
              [<b>[field:typelink/]</b>]
              <a href="[field:arcurl/]" class="title">[field:title/]</a>
            </h4>
          </div>
          [field:description/]...
        </div>