<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/111026/3-111026132A2.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/111026/3-111026132A2.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="710";
$z[1][4]['height']="474";
$z[2]=Array("img"," /uploads/allimg/111026/3-111026132A3.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/111026/3-111026132A3.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="710";
$z[2][4]['height']="398";
$z[3]=Array("img"," /uploads/allimg/111026/3-111026132A4.jpg ",387,532);
$z[3][4]['ddimg']="/uploads/allimg/111026/3-111026132A4.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="710";
$z[3][4]['height']="474";
$z[4]=Array("img"," /uploads/allimg/111026/3-111026132A5.jpg ",534,679);
$z[4][4]['ddimg']="/uploads/allimg/111026/3-111026132A5.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="710";
$z[4][4]['height']="366";

?>