<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/130501/245-130501063134.jpg ",93,261);
$z[1][4]['ddimg']="/uploads/allimg/130501/245-130501063134.jpg";
$z[1][4]['text']="赛后全家福";
$z[1][4]['width']="1342";
$z[1][4]['height']="8093";
$z[2]=Array("img"," /uploads/allimg/130501/245-130501063145.jpg ",263,430);
$z[2][4]['ddimg']="/uploads/allimg/130501/245-130501063145.jpg";
$z[2][4]['text']="场上真英雄";
$z[2][4]['width']="444";
$z[2][4]['height']="3259";

?>