<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/111026/3-111026115H4.jpg ",93,256);
$z[1][4]['ddimg']="/uploads/allimg/111026/3-111026115H4.jpg";
$z[1][4]['text']="会场座无虚席";
$z[1][4]['width']="800";
$z[1][4]['height']="531";
$z[2]=Array("img"," /uploads/allimg/111026/3-111026115P3.jpg ",258,409);
$z[2][4]['ddimg']="/uploads/allimg/111026/3-111026115P3.jpg";
$z[2][4]['text']="注册";
$z[2][4]['width']="800";
$z[2][4]['height']="531";
$z[3]=Array("img"," /uploads/allimg/111026/3-111026115P4.jpg ",411,556);
$z[3][4]['ddimg']="/uploads/allimg/111026/3-111026115P4.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="800";
$z[3][4]['height']="531";
$z[4]=Array("img"," /uploads/allimg/111026/3-111026115P5.jpg ",558,703);
$z[4][4]['ddimg']="/uploads/allimg/111026/3-111026115P5.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="800";
$z[4][4]['height']="531";
$z[5]=Array("img"," /uploads/allimg/111026/3-111026115P6.jpg ",705,850);
$z[5][4]['ddimg']="/uploads/allimg/111026/3-111026115P6.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="800";
$z[5][4]['height']="531";

?>