<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",18,95);
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",122,138);
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",140,225);
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",256,271);
$z[4]=Array("imgwidth","",285,303);
$z[5]=Array("linkurl","",366,382);
$z[6]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",384,470);
$z[6][4]['runphp']="yes";
$z[7]=Array("alttext","",490,506);
$z[8]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",546,626);
$z[8][4]['runphp']="yes";

?>