<div class="ca-list-img-div">
            <a href="[field:arcurl/]" class="pic"><img class="ca-list-image img-rounded img-polaroid" src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]"/></a>
            <h5 class="media-heading">
              <b><a href="[field:arcurl/]" class="title">[field:title/]</a></b>
            </h5>
            <small>最后更新：[field:pubdate function="GetDateMK(@me)"/]</small>
        </div>