<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/131112/245-131112035G1.jpg ",93,256);
$z[1][4]['ddimg']="/uploads/allimg/131112/245-131112035G1.jpg";
$z[1][4]['text']="哥大之声";
$z[1][4]['width']="1126";
$z[1][4]['height']="1592";

?>