<?php
$z[0]=Array("global","",146,171);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",237,262);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",324,349);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",382,408);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",536,563);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",636,663);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",666,692);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",1452,1479);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",1491,1523);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1546,1572);
$z[9][4]['name']="cfg_webname";

?>
<div style="display:none"><a href="http://www.cuasia.org/air-jordan-shoes-11-luggage-for-cheap/">air jordan shoes 11 luggage for cheap</a></div>