<?php
$z[0]=Array("global","",140,165);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",231,256);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",318,343);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",376,402);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",530,557);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",630,657);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",660,686);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",1441,1468);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",1480,1512);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1535,1561);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("global","",2210,2235);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("tag","\r\n        <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n      ",2816,2938);
$z[11][4]['row']="10";
$z[11][4]['getall']="1";
$z[11][4]['sort']="month";
$z[12]=Array("global","",3324,3349);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",3387,3630);
$z[13][4]['type']="top";
$z[13][4]['row']="10";
$z[13][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>