<?php
$z[0]=Array("include","",1513,1558);
$z[0][4]['filename']="./ca-neon/head.htm";
$z[1]=Array("arclist","\n          <div class=\"item active\">\n            <img src=\"[field:litpic/]\" alt=\"\">\n            <div class=\"carousel-caption\">\n              <h4>[field:title]</h4>\n              <p>[field:description function='cn_substr(@me,220)'/]...</p>\n              <a class=\"btn btn-large btn-primary\" href=\"[field:arcurl/]\">More</a>\n            </div>\n          </div>\n          ",2177,2604);
$z[1][4]['titlelen']="100";
$z[1][4]['flag']="f";
$z[1][4]['row']="1";
$z[2]=Array("arclist","\n          <div class=\"item\">\n            <img src=\"[field:litpic/]\" alt=\"\">\n            <div class=\"carousel-caption\">\n              <h4>[field:title/]</h4>\n              <p>[field:description function='cn_substr(@me,220)'/]...</p>\n              <a class=\"btn btn-large btn-primary\" href=\"[field:arcurl/]\">More</a>\n            </div>\n          </div>\n          ",2615,3040);
$z[2][4]['titlelen']="100";
$z[2][4]['flag']="f";
$z[2][4]['limit']="1,4";
$z[3]=Array("arclist","\n          <div class=\"ca-list\">\n            <a href=\"[field:arcurl/]\" class=\"ca-head\"><h4>[field:title/]</h4></a>\n            <p class=\"ca-listp\">[field:description function='cn_substr(@me,550)'/]...</p>\n          </div>\n          ",3519,3837);
$z[3][4]['typeid']="29";
$z[3][4]['titlelen']="36";
$z[3][4]['row']="5";
$z[3][4]['orderby']="id";
$z[3][4]['orderway']="desc";
$z[4]=Array("arclist","\n          <div class=\"ca-list\">\n            <a href=\"[field:arcurl/]\" class=\"ca-head\"><h4>[field:title/]</h4></a>\n            <p class=\"ca-listp\">[field:description function='cn_substr(@me,750)'/]...</p>\n          </div>\n          ",4050,4368);
$z[4][4]['typeid']="27";
$z[4][4]['titlelen']="56";
$z[4][4]['row']="5";
$z[4][4]['orderby']="id";
$z[4][4]['orderway']="desc";
$z[5]=Array("arclist","\n          <div class=\"ca-listi\">\n            <img class=\"ca-gallery-img img-rounded img-polaroid\" src=\"[field:litpic/]\" class=\"ca-gallery-img\"></img>\n            <a href=\"[field:arcurl/]\" class=\"ca-head\"><h4>[field:title/]</h4></a>\n          </div>\n          ",4587,4921);
$z[5][4]['typeid']="28";
$z[5][4]['row']="5";
$z[5][4]['orderby']="id";
$z[5][4]['orderway']="desc";
$z[6]=Array("include","",4951,4998);
$z[6][4]['filename']="./ca-neon/footer.htm";

?>