<?php
$z[0]=Array("field","",70,89);
$z[0][4]['name']="title";
$z[1]=Array("global","",90,116);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",293,351);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",471,500);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",840,885);
$z[4][4]['filename']="./ca-neon/head.htm";
$z[5]=Array("field","",1024,1053);
$z[5][4]['name']="position";
$z[6]=Array("list","\n        <div class=\"ca-list-img-div\">\n            <a href=\"[field:arcurl/]\" class=\"pic\"><img class=\"ca-list-image img-rounded img-polaroid\" src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\"/></a>\n            <h5 class=\"media-heading\">\n              <b><a href=\"[field:arcurl/]\" class=\"title\">[field:title/]</a></b>\n            </h5>\n            <small>最后更新：[field:pubdate function=\"GetDateMK(@me)\"/]</small>\n        </div>\n        ",1127,1625);
$z[6][4]['pagesize']="12";
$z[7]=Array("pagelist","",1707,1778);
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",1822,1869);
$z[8][4]['filename']="./ca-neon/footer.htm";

?>