<?php
$z[0]=Array("field","",70,89);
$z[0][4]['name']="title";
$z[1]=Array("global","",90,116);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1547,1592);
$z[2][4]['filename']="./ca-neon/head.htm";
$z[3]=Array("field","",1731,1760);
$z[3][4]['name']="position";
$z[4]=Array("list","\n        <div class=\"media ca-div-padding\">\n          [field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='pull-left'><img class='media-object' src='{@me['litpic']}'/></a>\"); [/field:array]\n          <div class=\"media-body ca-div-margin\">\n            <h4 class=\"media-heading\">\n              [<b>[field:typelink/]</b>]\n              <a href=\"[field:arcurl/]\" class=\"title\">[field:title/]</a>\n            </h4>\n          </div>\n          [field:description/]...\n        </div>\n        ",1817,2393);
$z[4][4]['orderby']="id";
$z[4][4]['pagesize']="10";
$z[5]=Array("pagelist","",2500,2571);
$z[5][4]['listitem']="info,index,end,pre,next,pageno";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",2615,2662);
$z[6][4]['filename']="./ca-neon/footer.htm";

?>