<?php  exit();
/*
Page: /member/index_do.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=51&mid=4
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2012-09-11 04:08:22
*/
?>
<?php  exit();
/*
Page: /plus/digg_ajax.php?id=51
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2012-09-11 04:08:22
*/
?>
<?php  exit();
/*
Page: /plus/feedback_ajax.php?dopost=getlist&aid=51&page=1
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2012-09-11 04:08:23
*/
?>
<?php  exit();
/*
Page: /plus/feedback.php?aid=15
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-02-13 19:39:20
*/
?>
<?php  exit();
/*
Page: /member/index_do.php?fmdo=user&dopost=regnew
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-03-16 22:28:58
*/
?>
<?php  exit();
/*
Page: /plus/count.php?view=yes&aid=95&mid=4
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-03-16 22:46:53
*/
?>
<?php  exit();
/*
Page: /plus/digg_ajax.php?id=95
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-03-16 22:46:54
*/
?>
<?php  exit();
/*
Page: /plus/feedback_ajax.php?dopost=getlist&aid=95&page=1
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-03-16 22:46:55
*/
?>
